### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by KarukSophia** [btwiusegentoo/chia-nix-hacky#1]
Hi I tried doing what you listed and it spat out this:
```
error: source tree referenced by 'git+file:///home/user/mnt/chia-test/chia-blockchain?ref=main&rev=59de4ffe9f98de62d281695d1f519d65ef2e2ece' does not contain a '/flake.nix' file
```
after typing nix develop

**Comment by btwiusegentoo** [comment]
Hi, sorry for bad documentation as I made just as repo to backup my nix files.
My guess below:
> A flake is (usually) a Git repository that contains a file named flake.nix at top-level.
https://gist.github.com/edolstra/40da6e3a4d4ee8fd019395365e0772e7
So, flake requires to have files added to git repository to detect them.
Therefore, you have to `git add flake.nix` `git add shell.nix`, that I forgot to write.
You don't have to commit them.
Also, note that I included some unnecessary packages like `python3Packages.dbus-python` for personally usage, tho I will remove them as I don't use these packages anymore. 
I think making `chia-blockchain` git submodule would be a better approach?
Hope this can help.

**Comment by KarukSophia** [comment]
Works really well. Thanks man!
